syntax = "proto3";

package memory_manager;

service MemoryManager {
  rpc Create (CreateRequest) returns (CreateResponse);
  rpc Set (SetRequest) returns (Empty);
  rpc Get (GetRequest) returns (GetResponse);
  rpc IncreaseRefCount (RefCountRequest) returns (Empty);
  rpc DecreaseRefCount (RefCountRequest) returns (Empty);
}

message CreateRequest {
  int32 size = 1;
  string type = 2;
}

message CreateResponse {
  int32 id = 1;
}

message SetRequest {
  int32 id = 1;
  string value = 2;
}

message GetRequest {
  int32 id = 1;
}

message GetResponse {
  string value = 1;
}

message RefCountRequest {
  int32 id = 1;
}

message Empty {}
